import { StoreKey, ToyProduct } from "./types";

export const STORE_LABELS: Record<StoreKey, string> = {
  lovehoney: "Lovehoney",
  adameve: "Adam & Eve",
  lelo: "LELO",
  womanizer: "Womanizer",
};

// ⚠️ Curated list: exactly 3 per store (for your "top rated 3" rule).
export const TOYS: ToyProduct[] = [
  // Lovehoney (3)
  {
    id: "lh-1",
    name: "Best Overall Pick",
    store: "lovehoney",
    type: "vibrators",
    useCases: ["beginners", "discreet"],
    short: "Simple, versatile, easy to recommend.",
    whyPicked: "Reliable favorite with broad appeal and easy controls.",
    rating: 4.8,
    reviewCount: 12000,
    buyUrl: "https://example.com/lovehoney-best-overall",
    imageUrl: "/images/toys/placeholder-neutral-1.jpg",
    priceNote: "Typically $50–$90",
  },
  {
    id: "lh-2",
    name: "Couples Favorite",
    store: "lovehoney",
    type: "couples",
    useCases: ["couples", "discreet"],
    short: "Designed for shared sessions.",
    whyPicked: "Comfortable shape and strong 'together' use case.",
    rating: 4.7,
    reviewCount: 8000,
    buyUrl: "https://example.com/lovehoney-couples",
    imageUrl: "/images/toys/placeholder-neutral-2.jpg",
    priceNote: "Typically $80–$140",
  },
  {
    id: "lh-3",
    name: "Air Pulse Choice",
    store: "lovehoney",
    type: "air_pulse",
    useCases: ["premium", "discreet"],
    short: "Air pulse stimulation, premium feel.",
    whyPicked: "High satisfaction for people who prefer air pulse.",
    rating: 4.6,
    reviewCount: 6000,
    buyUrl: "https://example.com/lovehoney-air-pulse",
    imageUrl: "/images/toys/placeholder-neutral-3.jpg",
    priceNote: "Typically $99–$169",
  },

  // Adam & Eve (3)
  {
    id: "ae-1",
    name: "Best Value Pick",
    store: "adameve",
    type: "vibrators",
    useCases: ["beginners"],
    short: "Solid performance without the premium price.",
    whyPicked: "Best bang-for-buck while staying body-safe and dependable.",
    rating: 4.7,
    reviewCount: 15000,
    buyUrl: "https://example.com/adameve-best-value",
    imageUrl: "/images/toys/placeholder-neutral-4.jpg",
    priceNote: "Typically $30–$70",
  },
  {
    id: "ae-2",
    name: "Discreet Travel Option",
    store: "adameve",
    type: "accessories",
    useCases: ["discreet"],
    short: "Compact, quiet, easy to store.",
    whyPicked: "A strong discreet option with good real-world usability.",
    rating: 4.6,
    reviewCount: 9000,
    buyUrl: "https://example.com/adameve-discreet",
    imageUrl: "/images/toys/placeholder-neutral-5.jpg",
    priceNote: "Typically $25–$60",
  },
  {
    id: "ae-3",
    name: "Beginner-Friendly Anal Option",
    store: "adameve",
    type: "anal",
    useCases: ["beginners", "discreet"],
    short: "Beginner-sized, simple, body-safe.",
    whyPicked: "A careful beginner pick with comfort-focused design.",
    rating: 4.5,
    reviewCount: 7000,
    buyUrl: "https://example.com/adameve-anal-beginner",
    imageUrl: "/images/toys/placeholder-neutral-6.jpg",
    priceNote: "Typically $20–$50",
  },

  // LELO (3)
  {
    id: "lelo-1",
    name: "Luxury Classic",
    store: "lelo",
    type: "vibrators",
    useCases: ["premium"],
    short: "Premium build, understated design.",
    whyPicked: "Luxury materials and strong brand reputation.",
    rating: 4.8,
    reviewCount: 5000,
    buyUrl: "https://example.com/lelo-luxury-classic",
    imageUrl: "/images/toys/placeholder-neutral-7.jpg",
    priceNote: "Typically $129–$199",
  },
  {
    id: "lelo-2",
    name: "Couples Premium",
    store: "lelo",
    type: "couples",
    useCases: ["couples", "premium"],
    short: "Elevated couples design.",
    whyPicked: "A premium couples pick with refined ergonomics.",
    rating: 4.7,
    reviewCount: 3500,
    buyUrl: "https://example.com/lelo-couples",
    imageUrl: "/images/toys/placeholder-neutral-8.jpg",
    priceNote: "Typically $149–$249",
  },
  {
    id: "lelo-3",
    name: "Discreet Premium",
    store: "lelo",
    type: "accessories",
    useCases: ["discreet", "premium"],
    short: "Minimal, quiet, travel-friendly.",
    whyPicked: "Discreet luxury option for people who want subtle design.",
    rating: 4.6,
    reviewCount: 2800,
    buyUrl: "https://example.com/lelo-discreet",
    imageUrl: "/images/toys/placeholder-neutral-9.jpg",
    priceNote: "Typically $99–$179",
  },

  // Womanizer (3)
  {
    id: "wz-1",
    name: "Air Pulse Flagship",
    store: "womanizer",
    type: "air_pulse",
    useCases: ["premium", "discreet"],
    short: "Air pulse stimulation with premium finish.",
    whyPicked: "Flagship-level satisfaction for air pulse fans.",
    rating: 4.8,
    reviewCount: 10000,
    buyUrl: "https://example.com/womanizer-flagship",
    imageUrl: "/images/toys/placeholder-neutral-10.jpg",
    priceNote: "Typically $149–$249",
  },
  {
    id: "wz-2",
    name: "Best Mid-Tier Air Pulse",
    store: "womanizer",
    type: "air_pulse",
    useCases: ["premium"],
    short: "Balanced performance and price.",
    whyPicked: "Great sweet spot model for most people.",
    rating: 4.7,
    reviewCount: 7000,
    buyUrl: "https://example.com/womanizer-mid",
    imageUrl: "/images/toys/placeholder-neutral-11.jpg",
    priceNote: "Typically $99–$179",
  },
  {
    id: "wz-3",
    name: "Discreet Air Pulse",
    store: "womanizer",
    type: "air_pulse",
    useCases: ["discreet"],
    short: "Compact and quiet.",
    whyPicked: "A discreet pick that still keeps the core experience.",
    rating: 4.6,
    reviewCount: 6000,
    buyUrl: "https://example.com/womanizer-compact",
    imageUrl: "/images/toys/placeholder-neutral-12.jpg",
    priceNote: "Typically $79–$149",
  },
];
